"""add mobile filed

Revision ID: 42c7486a5db2
Revises: 6050bb14695e
Create Date: 2025-12-01 20:07:29.714820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c7486a5db2'
down_revision: Union[str, Sequence[str], None] = '6050bb14695e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###
